version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            pip install --no-cache-dir -r requirements.txt
            python setup.py install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            make build -B
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push emptymalei/$IMAGE_NAME:$TAG
