version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
         docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Setup Environment
          command: |
            apt-get update
            apt-get install -y software-properties-common vim
            add-apt-repository ppa:jonathonf/python-3.6
            apt-get update
            apt-get install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv
            pip install --no-cache-dir -r requirements.txt
            python setup.py install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            make build -B
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push emptymalei/$IMAGE_NAME:$TAG
