version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            apt-get update
            apt install -y docker.io
      - run:
          name: Setup Environment
          command: |
            apt-get update
            apt-get install -y software-properties-common vim
            apt install -y python3-pip
            alias pip=pip3
            pip3 install --no-cache-dir -r requirements.txt
            python3 setup.py install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            alias pip=pip3
            make build -B
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push emptymalei/$IMAGE_NAME:$TAG
